---
version: 2
jobs:
  build:
    docker:
      - image: gcr.io/cloud-devrel-public-resources/python:latest
    steps:
      - checkout
      - run:
          name: Add GitHub public key to known hosts
          command: |
            mkdir -p ~/.ssh/
            if [[ ! -f ~/.ssh/known_hosts ]] || ! grep "github.com" ~/.ssh/known_hosts; then
              echo "
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
              " >> ~/.ssh/known_hosts
            fi
      - run:
          name: Make sure google-cloud setup.py is valid
          command: |
            nox -s lint_setup_py
      - deploy:
          name: Update the docs
          command: nox -s docs
    working_directory: /var/code/gcp/

deployment:
  tag_build_for_cci2:
    # 1.0 style config for tag builds workaround
    # For context, see:
    # - https://discuss.circleci.com/t/build-on-tag/9864/30
    # - https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
    # - https://circleci.com/gh/keybits/circulate/58#config/containers/0
    # See "test_utils/scripts/circleci/get_tagged_package.py" for info on REGEX
    tag: /(([a-z]+)-)*([0-9]+)\.([0-9]+)\.([0-9]+)/
    commands:
      - true
